name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Déclencher ce workflow sur les pushs vers la branche main

jobs:
  build:
    runs-on: ubuntu-latest  # Utiliser la dernière version d'Ubuntu

    steps:
    - name: Checkout code  # Étape pour récupérer le code source
      uses: actions/checkout@v2

    - name: Set up Python 3.8  # Étape pour configurer Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies  # Étape pour installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests  # Étape pour exécuter les tests
      run: |
        pytest  # Assurez-vous que vous avez des tests unitaires dans votre projet
